[package]
name = "prob01"
version = "0.1.0"
authors = ["Ezekiel Chopper <ezekiel.chopper@workday.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
